name: Automatic JIRA Ticket Creation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  create-jira-ticket:
    name: Create JIRA Ticket
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create JIRA Ticket
      id: create-jira
      uses: atlassian/gajira-create@v2
      with:
        project: CONUPDATE
        issuetype: Task
        summary: |
          Github PR - nd104 Programming for Data Science | Repo: pdsnd_github (Post your Work on Github) | PR# ${{ github.event.pull_request.number }}
        description: |
          Repo link: ${{ github.repository.html_url }}
          PR no. ${{ github.event.pull_request.number }}
          PR title: ${{ github.event.pull_request.title }}
          PR description: ${{ github.event.pull_request.body }}
          In addition, please resolve other issues, if any. See a sample responses here: ${{ github.event.pull_request.html_url }} and close the PR.
        fields: '{"components": [{"name":"Github PR"}], "customfield_16449":"https://classroom.udacity.com/nanodegrees/nd104/parts/912d84b6-bf81-4311-8e00-b3b2f63dc965/modules/07253c48-aa80-4701-8acf-3629088e2d98/lessons/e9652698-f014-4e98-b9dc-c89a868d9860/concepts/f7ab906b-d9e1-4444-806d-3e8d90324598", "customfield_16450":"Resolve the PR", "labels": ["github"]}'

    - name: Log created issue
      run: echo "Issue ${{ steps.create-jira.outputs.issue }} was created"
